### ISSUE TITLE
Not working with one single item

### ISSUE THREAD

**Issue by svenadlung** [lluz/jquery-conveyor-ticker#1]
@lluz really nice work! I am just wondering if there is a way to make it work with a single item as well? It should just repeat the one item again and again.

**Comment by lluz** [comment]
Hi @svenadlung.
Thank you.

Just submitted "v.1.0.2.beta"
Please test it and give me some feedback if it responds to your needs.

Notes:
Added the option 'force_loop'. When set to 'true' should do the replication and trigger the init.

Best regards.

**Comment by svenadlung** [comment]
Hi @lluz thank you so much! It looks good to me!

**Comment by lluz** [comment]
Hi @svenadlung, ok and thanks for the help. Release "released" :)
